name: Publish plugin to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - plugin@*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
          registry-url: https://registry.npmjs.org
          scope: '@sepveneto'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Update npm
        run: npm install npm@11.6.1 -g

      - name: Get Version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/plugin@}" >> $GITHUB_ENV

      - name: Build and Publish
        run: sh ./scripts/publish-plugin.sh
        env:
          NODE_AUTH_TOKEN: ''
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
